name: Deploy Lambda Function

on:
    #paths:
    #  - "src/**"

  workflow_dispatch:
    inputs:
      tag:
        description: 'New tag name'
        required: true
    
jobs:
  
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda Function
        run: cd src && zip -r code.zip .

      - name: Deploy to AWS Lambda
        run: | 
          aws lambda update-function-code \
          --function-name cicd_version_alias_test \
          --zip-file=fileb://src/code.zip
      
      - name: Update alias lambda
        run: | 
          aws lambda update-alias \
          --function-name cicd_version_alias_test --name dev --function-version ${{ github.event.inputs.tag }}

  staging:
    runs-on: ubuntu-latest
    environment: staging
    needs: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda Function
        run: cd src && zip -r code.zip .

      - name: Deploy to AWS Lambda
        run: | 
          aws lambda update-function-code \
          --function-name ${{ secrets.AWS_ARN_LAMBDA }} \
          --zip-file=fileb://src/code.zip
  
  prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create Release
        id: prod
        uses: actions/create-release@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install zip tool
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda Function
        run: cd src && zip -r code.zip .

      - name: Deploy to AWS Lambda
        run: | 
          aws lambda update-function-code \
          --function-name ${{ secrets.AWS_ARN_LAMBDA }} \
          --zip-file=fileb://src/code.zip
